
version: '2'

services:
  dyndns-godaddypy:
    container_name: dyndns-godaddypy
    restart: always
    build: .
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "10"

    environment:
      - DGDP_DOMAIN=example.com
      - DGDP_RECORDTYPE=A
      - DGDP_APIKEY=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      - DGDP_APISECRET=XXXXXXXXXXXXXXXXXXXXXX
      - DGDP_SUBDOMAINS=subdmain1,subdomain2,subdomain3
      - DGDP_SLEEPTIME=150
      - DGDP_MAILFROM=example@mail.com
      - DGDP_MAILTO=example@mail.com
      - DGDP_MAILSUBJECT='Mail Subject'
      - DGDP_SENDMAIL=False
      - DGDP_SMTPSERVER=smtp.gmail.com
      - DGDP_SMTPPORT=587
      - DGDP_SMTPUSER=user
      - DGDP_SMTPPASSWORD=pass
      - PYTHONUNBUFFERED=0

