
version: '2'

services:
  dyndns-godaddypy:
    container_name: dyndns-godaddypy
    restart: always
    build: .
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "10"

    environment:
      - DGDP_DOMAIN=example.com
      - DGDP_RECORDTYPE=A
      - DGDP_APIKEY=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      - DGDP_APISECRET=XXXXXXXXXXXXXXXXXXXXXX
      - DGDP_SUBDOMAINS=subdmain1,subdomain2,subdomain3
      - DGDP_SLEEPTIME=300
      - PYTHONUNBUFFERED=0

