
version: '2'

services:
  dyndns-godaddypy:
    restart: always
    build: .
    environment:
      - DGDP_DOMAIN=example.com
      - DGDP_RECORDTYPE=A
      - DGDP_APIKEY=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      - DGDP_APISECRET=XXXXXXXXXXXXXXXXXXXXXX
      - DGDP_SUBDOMAINS=subdmain1,subdomain2,subdomain3
      - DGDP_SLEEPTIME=300
      - PYTHONUNBUFFERED=0

